### ISSUE TITLE
Broken link to play in browser in 'Demos & Tutorials'

### ISSUE THREAD

**Issue by SonicGDX** [libgdx/libgdx.github.io#146]
Here https://libgdx.com/wiki/start/demos-and-tutorials
at the end there is a broken link to "try all these demos [right in your browser!](https://libgdx.badlogicgames.com/demos/"

The demos that are linked to also have broken links in their github readme and have issues mentioning those, but I thought I'd put another issue here because the wiki also has a direct broken link. I don't think any of the broken links have been mirrored anywhere.

**Comment by crykn** [comment]
Thanks for reporting the broken link! Regarding the demos in general, there is a somewhat larger discussion to be had, see libgdx/libgdx#6964. Ideally, we'd bring all (or at least some) of the demos up to date and then host them via GH Pages, but so far no one had the time and/or interest to look into this.
