### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx.github.io#163]
There's no licence file in this repository and the website itself doesn't tell me much more than "© 2023 libGDX". Can it be clarified what we're contributing under? I don't care about this as much as it might come across - it just crossed my mind, that's all.

**Comment by yuripourre** [comment]
![Screenshot_20231107-085431](https://github.com/libgdx/libgdx.github.io/assets/1824878/1b0e40d3-c052-41a4-a867-e919017dae13)

**Comment by yuripourre** [comment]
Nvm, you are talking about the libgdx.github.io repo.

**Comment by Frosty-J** [comment]
Haha, yeah. The main repository is also a bit murky, but generally GDX is Apache and that's already covered at #6663.

**Comment by crykn** [comment]
If no-one has any objections, new contributions are now licensed under the CC BY-SA. Old contributions (either to this repo, the original wiki or the old website) can't be re-licensed by us, so they stay under their respective terms (which are those specified under section D.5 of the GitHub TOS as well as the ones implicitly granted by contributing to a public website/documentation).
