### ISSUE TITLE
Versions page to be updated

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx.github.io#169]
I don't know what versions of things we're on now, or how relevant this page even is when gdx-setup isn't tied to the libGDX release cycle, other than that libGDX 1.12.0 is old news.

https://libgdx.com/dev/versions/

**Comment by crykn** [comment]
The version data is automatically updated on every build via a [custom Jekyll plugin](https://github.com/libgdx/libgdx.github.io/blob/dev/_plugins/libgdx_fetch_versions.rb), which depends on gdx-setup's version bank having the correct values... I guess, I'll have to update it manually for now and hope I don't forget to undo that change after the next release.

**Comment by crykn** [comment]
Closed by f055d61.
