### ISSUE TITLE
incorrect package name

### ISSUE THREAD

**Issue by Codyjtx** [libgdx/libgdx.github.io#174]
For the simple game tutorial located inside 
wiki/start/a-simple-game.md
desktoplauncher.java should be packaged as 'package com.badlogic.drop;' instead of 'package com.badlogic.drop.Desktop;'

**Comment by Frosty-J** [comment]
Same story with the Android package - `package com.badlogic.drop.android` does not match the project generator.

I think it's outdated - someone will be in a real pickle if they copy & paste `<uses-sdk android:minSdkVersion="8" android:targetSdkVersion="20" />`.
