### ISSUE TITLE
libgbx/l. iibgdx.g. ithub.io

### ISSUE THREAD

**Issue by Astra4587** [libgdx/libgdx.github.io#188]
Ошибка.
ilbgdx/l. Iibgdx.g. ithub.io
Владелец, разработчик Astra 4587.diff.

**Comment by Frosty-J** [comment]
I don't understand why your forks and this issue title are named in such funny ways as https://github.com/Astra-33-57/Iibgdx-l-ibgdx.g.-ithub.-io or why you keep trying to append `Владелец, разработчик Astra 4587.diff` ("Owner, developer"?) to the index page (#185, #187). Needless to say, that is not an appropriate addition to the libGDX wiki. Please leave it alone - this will just be classed as spam if there isn't at least evidence of good intentions.

![image](https://github.com/libgdx/libgdx.github.io/assets/60154347/c493f5fc-9976-4083-abb2-e9e9dcb3d8fa)
