### ISSUE TITLE
Shortcut to roadmap

### ISSUE THREAD

**Issue by fabiitch** [libgdx/libgdx.github.io#20]
Hello, congratulations to the new website, i love it.

I think a shortcut  to your roadmap is missing !

Actually for see it i use uri.

thanks for reading

**Comment by crykn** [comment]
Hey @fabiitch! 

A link to the roadmap can be found under [`Documentation`](https://libgdx.com/dev/) > `Contributing to libGDX` (sidebar) > `Roadmap`. But you're right, it is kind of hard to find. I'll have a look whether I can come up with a better place for the link.

Best regards!
