### ISSUE TITLE
Add 'Dash till Puff 2' in showcase application

### ISSUE THREAD

**Issue by fabiitch** [libgdx/libgdx.github.io#22]
Hi, i dowload this game some years ago, and i see "Powered by LibGdx" in credits.
The game is of good quality and got a lot of review and dowload on play store

link website : [https://riftergames.com/dash-till-puff-2/](url) 
link google play : [https://play.google.com/store/apps/details?id=com.riftergames.dtp2.android&hl=fr&gl=US](url) 
Link app store  : [https://apps.apple.com/fr/app/dash-till-puff-2/id991660396](url)

I want to clarify, Its not my game ^^
close it if you think its no value.

I join a screen of credits
![image](https://user-images.githubusercontent.com/12832996/106579764-59466f80-6541-11eb-8061-b2f6577efd77.png)

Thanks for reading

**Comment by obigu** [comment]
That's my game! :D

**Comment by fabiitch** [comment]
@obigu ooh nice work =), i have spend a lot of time on it.
