### ISSUE TITLE
Demo page is down

### ISSUE THREAD

**Issue by john-sardinha-pbx** [libgdx/libgdx.github.io#222]
Please ensure you have given all the following requested information in your report.

#### Issue details
https://libgdx.badlogicgames.com/demos/ is down (503)

#### Reproduction steps/code
Go to https://libgdx.badlogicgames.com/demos/ 

```
> $ ping https://libgdx.badlogicgames.com/demos
ping: cannot resolve https://libgdx.badlogicgames.com/demos: Unknown host
> $ ping https://libgdx.badlogicgames.com                                                                                                                                            X
PING https://libgdx.badlogicgames.com (95.216.8.184): 56 data bytes
64 bytes from 95.216.8.184: icmp_seq=0 ttl=53 time=46.012 ms
64 bytes from 95.216.8.184: icmp_seq=1 ttl=53 time=45.540 ms
```

#### Version of libGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by crykn** [comment]
Closing this in favour of #221.
