### ISSUE TITLE
Switch to gradle run instead of setting up a new launch configuration

### ISSUE THREAD

**Issue by lyze237** [libgdx/libgdx.github.io#32]
In IntelliJ, instead of setting up a launch configuration, you can extend the gradle tab, then click on the run task.

This sets up a run configuration for you automatically.

Advantage is that the user can't mess up the working directory or anything else and it gets them familiar with the gradle tasks window. Therefore, it (should) be easier to run other tasks, like dist and clean.

![image](https://user-images.githubusercontent.com/11274700/115534492-21291000-a298-11eb-8b7e-23c519e74669.png)

**Comment by mgsx-dev** [comment]
Disadvantage is that you can't provide various program arguments via various launchers, i guess both way have their pros/cons and should be documented there.

**Comment by Tom-Ski** [comment]
You also are forced to run with Gradle, so you miss out on nice features like hotswap

**Comment by lyze237** [comment]
Reloading classes work just fine during runtime via gradle/debugging.

![image](https://user-images.githubusercontent.com/11274700/115543927-3b67eb80-a2a2-11eb-96e1-00e016a5480f.png)

**Comment by crykn** [comment]
Does 74057bd6470567422ac3274e58facdb30c4046ed satisfy everybody? It is visible here: https://libgdx.com/dev/import-and-running/#in-ideaandroid-studio

**Comment by lyze237** [comment]
Looks good yeah, thanks! :)
