### ISSUE TITLE
Code of MainMenuScreen.kt is copied from GameScreen.kt

### ISSUE THREAD

**Issue by rahul-lohra** [libgdx/libgdx.github.io#33]
Hi, the code of MainMenuScreen.kt is copied from GameScreen.kt, kindly fix it

You can use this gist for reference - 
[MainMenuScreen.kt](https://gist.github.com/rahul-lohra/57d8b1daf4d914dbbd11f2a610b241c9#file-mainmenuscreen-kt)

**Comment by crykn** [comment]
Thanks for reporting this!
