### ISSUE TITLE
Removal of IRC

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx.github.io#40]
At https://libgdx.com/community/ it says libGDX has an IRC channel on Freenode. I've heard the libGDX community has been nonexistent there for a good while, and ever since Freenode officially become digital territory of the Joseon Empire, things have gone downhill across the entire network.

I've been discussing this in #libgdx-contributions on Discord and have proposed the removal of a reference to it at https://github.com/libgdx/libgdx/pull/6627. It may make sense to remove this from the website, too (or at least say the libGDX community *used to* be on IRC).

Could theoretically do it myself but would need to figure out how to do so without ruining the layout. Just not going to invest the time right now, unfortunately.

**Comment by tommyettinger** [comment]
Insolent commoner! How dare you defy the will of [HIH Andrew Lee, descended by blood from... some minor empire in the footnotes of history](https://freenode.net/)?

Yeah, screw Freenode, and scrub any references to it. Linking to Freenode is the sign of a dead project.

**Comment by crykn** [comment]
This makes sense, thanks for mentioning it, @Frosty-J!
