### ISSUE TITLE
Mirror/Move the current libGDX wiki to GitHub Pages?

### ISSUE THREAD

**Issue by Spaio** [libgdx/libgdx.github.io#58]
Github wiki is not getting indexed by search crawlers.
To solve this problem, ive made a repository which clones Libgdx Wiki and transfers all resources to Github Pages.
Repository:
https://github.com/Spaio/libgdx-wiki-on-pages
Pages link:
https://spaio.github.io/libgdx-wiki-on-pages/wiki/

Currently it mostly like alpha version, but all links working properly, no issues with content found.
In next week i plan to complete it by adding back links for original wiki, performing better styling and SEO optimisation. 

In combination with GitHub Wiki what my solution gives:
- Easy editing of wiki. No need for pull requests, everyone could easily contribute.
- Full copy of original wiki content optimised for search crawlers.
- Automatic builds. Takes 15 seconds to react on any change.
- Can be deployed under any web address.

The question is, am i allowed to get it combined with any official Libgdx resources? It could be:
1) Subdomain of main website
2) Link on main website
3) Usage of libgdx.wiki  domain. It is owned by some of Libgdx contributors as i understand.

Original wiki
![image](https://user-images.githubusercontent.com/93801803/140622054-0149e863-c9a9-4e04-bf3d-ad500d08be3f.png)

Github pages version
![image](https://user-images.githubusercontent.com/93801803/140622034-138110e4-90f3-466c-b3d5-deac97c3a35f.png)

**Comment by crykn** [comment]
Hi @Spaio,

Thanks for bringing this up and the work you've already done! 

The fact that Google and other search engines are (no longer) indexing our wiki pages is definitely a problem. However, I think instead of mirroring the wiki to a GitHub Pages site, we should just discontinue the wiki and move its entries to its own GitHub Pages site. This would cut out the middle man (AFAIK the mirroring has to triggered manually atm) and would also give us access to HTML & JS stuff on the page. This could be used – amongst other things – to embed libGDX GTW examples in the wiki. The only drawback to this solution is that changes to the wiki would require a PR, but as most people contributing to the wiki are regulars, I don't think that that will prove as too much of a problem. 

Whether it makes sense to host those wiki pages via a directory in this repo or whether we should create a separate one, I'm not sure.

**Comment by raeleus** [comment]
I really like the idea of being able to embed GWT examples into the pages. That would reduce a lot of confusion and make the wiki more attractive as a learning resource. I would definitely want to contribute to that.

**Comment by Frosty-J** [comment]
> AFAIK the mirroring has to triggered manually atm

It wouldn't have to be. I'm unaware of a way to run an Action after a wiki page is edited, but one could be scheduled that checks for changes, then does something if there are any. This would mean wiki changes wouldn't immediately be reflected on the website, but I'm sure it would still be good enough.

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events

**Comment by Spaio** [comment]
Thank you for answering me. 

Im not sure what exactly meant under moving to github pages and who would do that. In case thats not supposed to be me, i would mention next few sentences. 
I came up by myself with such solution because i asked what can we do in discord. And it looks for me that the main problem is that nobody wants to take care of it. I would give a complete solution and none of Libgdx contributors would need to write a single line of code to adjust anything. 

The same replication algorithm  could be applied for Wikis of different Libgdx related libraries. They could be easily placed on same website together with Libgdx wiki.
Example:
https://github.com/raeleus/skin-composer/wiki
Written so much useful information but its not getting indexed by google and its just terrible.

Beside that, if you would like to move out from Github Wiki that means that you have to use certain website engine or something. Even though the Github Pages built-in Jekyll would be used, it will require additional work for some aspects such as validation of pages index consistency and replacement of some Wiki-specific syntax parts (such as [[ links).
The Libgdx Github Wiki has a hierarchy problem. Its flat and all pages lie under same folder. Im very limited in knowledges about Github Wiki in general, but if there are none solution for that, moving out would be a great option. It would give an opportunity for automatic indexation for Table Of Content and better navigation possibilities. Despite that it will require additional work for sure.

The automation of replication is not a problem at all. There is definitely some hook to get notified about wiki pages changes. But if there is none, its easy and efficient enough to get replication automatically initiated each hour or each day.

During the time i was writing this comment, i started to understand that moving Libgdx Wiki to Pages would be a good option. And for the rest of Libgdx related Wikis they just would be replicated in a manner how its done now. It wont require the work from their creators. 

I have a wish and time to finish the Wiki replication how its been described. I have understanding of how much work i need to do. 
In case the Wiki could be moved to pages, there is possibility that i wont have an opportunity to do it alone. 
And i do not pretend to have ownership on repository at all. Im far from contributions in general and it just would be better if there will be no dependency on me as an exclusive owner.

**Comment by crykn** [comment]
I have had some time to look into this and the result can be found at: https://crykn.github.io/wiki/

There are still some kinks that need to be worked out (see the list in the corresponding repo: https://github.com/crykn/crykn.github.io#todo; pull requests are appreciated), but it's a sound basis. And @Spaio's `WikiToPagesTranslator.java` file proved to be a very useful, so thanks for that!
