### ISSUE TITLE
Canonical links should be absolute

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx.github.io#62]
If we take the homepage, for example, we have `<link rel="canonical" href="/">`. That's fine - I think it'll stop search engines from thinking libgdx.com/?aaaaaa might be the proper address, but what it doesn't do is stop them from thinking crykn.github.io might be the proper address. Sometimes it wins in the rankings, but only rarely - you have to go out of your way to make it happen since libgdx.com will hopefully always have more domain authority.

[![crykn.github.io ranking at the top for the search query "GDX is always written in upper-case" on Bing](https://user-images.githubusercontent.com/60154347/143794370-a91a7949-c336-4b85-8313-e66095208112.png)](https://www.bing.com/search?q=GDX+is+always+written+in+upper-case+letters)

But changing this I'm not too sure on. It's a part of `seo.html` I'm sure, but that file appears out of thin air.

https://github.com/libgdx/libgdx.github.io/blob/965436cc4aace51d740f9714c0788968c356c95a/_includes/head.html#L5

**Comment by crykn** [comment]
Good find! Ideally, crykn.github.io won't be online much longer. @Spaio is working on some wiki improvements and then it'll be merged. 

The `seo.html` file is part of the Minimal Mistakes theme: [_includes/seo.html](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/seo.html). Apparently, the canonical URL can be set [via the frontmatter](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#canonical-url):
```md
canonical_url: "https://yoursite.com/custom-canonical-url"
```
