### ISSUE TITLE
Embed GWT apps

### ISSUE THREAD

**Issue by crykn** [libgdx/libgdx.github.io#68]
As mentioned in [Status Report #8](https://libgdx.com/news/2022/01/devlog-8-wiki-migration), it would be pretty cool to embed GWT content in wiki pages. This issue is meant as a RFC on how to implement this best. If anyone wants to give this a shot, please feel free to do so.

- The generated JS code should be located somewhere in `/assets/wiki/`
- A custom embed-gwt element should be created to make usage as simple as possible. Something like: `{% include gwt.html path='/assets/wiki/gwt/example1/' %}`. See [here](https://github.com/libgdx/libgdx.github.io/blob/dev/_includes/status.html) for a very basic example of an element.
- The embed-gwt element then has to take care of adding the needed HTML code as well as the Javascript script (just take a look at the index.html generated by a libGDX GWT project; maybe [this blog post](https://madelinemiller.dev/blog/embed-gwt-in-react/) can give some pointers).
- The GWT application itself seems to require some (asset) path changes. 
- Suggested by @Frosty-J: Java source code located somewhere in the project (maybe in a `/gwt/` folder in the root) could be auto-compiled [via GitHub Actions](https://github.com/libgdx/libgdx.github.io/tree/dev/.github/workflows), modified as necessary and copied to the `/assets/wiki/gwt/` path. (Maybe this specific action should only run if triggered manually or when there are [changes to the corresponding dir](https://stackoverflow.com/a/63461325).)

**Comment by Frosty-J** [comment]
> Maybe this specific action should only run if triggered manually or when there are changes to the corresponding dir.

I strongly agree with this. A simple jam game of mine (and DeveloperDoge) takes about two minutes to do a GWT build on GitHub Actions. The project includes freetype and shapedrawer but no other libraries. If the wiki had even just a few apps, and they all compiled on each build, the job time would quickly accumulate.

**Comment by Raxorg** [comment]
What about a repo containing all the samples in separate folders, publishing a gh-pages site with them, and then accessing each sample like this
```html
Some wiki text...
<iframe src='https://libgdx.github.io/samplesrepo/sample1/'></iframe>
Some wiki text...
<iframe src='https://libgdx.github.io/samplesrepo/sample2/'></iframe>
Some wiki text...
```
after talking to @lyze237 it seems possible

**Comment by lyze237** [comment]
I've just written up a tiny little script and gh action which can do that.

It finds all html projects and builds them, then copies them (while keeping the folder structure in tact) into the gh-pages branch.

https://github.com/lyze237/libgdx-examples-demo

Example links:
From: https://github.com/lyze237/libgdx-examples-demo/tree/gh-pages/A/B/Thing
To: https://lyze237.github.io/libgdx-examples-demo/A/B/Thing/index.html

From: https://github.com/lyze237/libgdx-examples-demo/tree/gh-pages/Thing%20-%20Copy%20(2)
To: https://lyze237.github.io/libgdx-examples-demo/Thing%20-%20Copy%20(2)/index.html

And so on...

**Comment by crykn** [comment]
Thanks! I just added the `embed-gwt` element and created a [libgdx-wiki-examples](https://github.com/libgdx/libgdx-wiki-examples) repo. Instructions on how to use all of this can be found in the Wiki Style Guide.
