### ISSUE TITLE
Duplicate meta descriptions

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx.github.io#78]
Currently, all pages on the libGDX website have the same meta description. Fortunately, search engines often ignore this, but not always. Here we have a Google search:

> ![Three Google search results, all with the description "libGDX is a cross-platform Java game development framework based on OpenGL (ES) that works on Windows, Linux, macOS, Android, your browser and iOS."](https://user-images.githubusercontent.com/60154347/154865968-52f3f274-ea5a-4ffa-81db-91b9cfaf5e16.png)

If instead each page had a different description, it would look more varied and less spammy. Here I've replaced the descriptions with the first paragraph of each page, complete with strange grammar. They aren't real results:

> ![Three Google search results, all with different descriptions](https://user-images.githubusercontent.com/60154347/154865969-86a553e9-c79c-4555-9e95-e172a8afc816.png)

If these then got truncated (e.g. "Acceleration is measured in ...") that may increase click-through rate, though I have no evidence to back this up.

I'm not proposing we handwrite a description for each and every page (though it might not be a bad idea for the most prominent pages) but rather that the descriptions are generated from the page content. That, or scrap them altogether and hope the search engines don't decide the navigation is the most interesting part of the page.

P.S. Screw you, GitHub. This has to be the only website that doesn't confirm if you want to save your work (or just automatically save it) before leaving the page.

**Comment by crykn** [comment]
Interestingly enough, the accelerator page has a proper Google description on my end:
![acc](https://user-images.githubusercontent.com/8125827/154869593-8b41324e-5724-46e7-a9da-aba1dc81782e.png)

But going forward, the above commit should provide the wiki pages with more meaningful descriptions by default.

**Comment by Frosty-J** [comment]
Yes, Google at the least tries to keep the descriptions as relevant as possible. If I search for "libgdx accelerometer" I get the same as you. If I search for "site:libgdx.com/wiki/", I don't. If I search for '"Unfortunately, this configuration is different for tablets"' the description begins at the quoted query.
