### ISSUE TITLE
`old_releases` directory is big

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx.github.io#84]
Whenever I clone this repository, even a shallow clone, it takes a good while due to the `old_releases` directory being 349MB in size.

Furthermore, it is missing [`libgdx-0.9.2.zip`](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/libgdx/libgdx-0.9.2.zip), making it an incomplete collection of pre-1.0 releases. I don't know if anything else is missing or if the version numbers are just odd (no `0.9.5`, for example).

I like the idea of ensuring old releases don't get lost to time - I'd just prefer if they weren't in the development branch. End of rant.

**Comment by crykn** [comment]
That seems like a valid concern. Removing the binaries will involve rewriting the past git history, which is always a bit of a hassle, but I'll look into this, when I find some time.

**Comment by Frosty-J** [comment]
I use `--depth 1` when cloning thanks to what a whopper libgdx/libgdx's history is (over a gigabyte, I recall). So in my personal case it wouldn't really matter if history isn't rewritten, instead only the present.

But it would be nice if you're willing to purge stuff from the commit history. Don't suppose there's a huge risk in it, with the small amount of contributors this repository sees.

**Comment by crykn** [comment]
> So in my personal case it wouldn't really matter if history isn't rewritten, instead only the present.

Okay, I've pushed a preliminary fix for this and will take a look at rewriting the history at a later date.
