### ISSUE TITLE
Copying code to clipboard would be rad

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx.github.io#88]
Okay, had my lunch now. Ready for imports. Don't know how difficult this would be to implement, but on GitHub you can copy code blocks to the clipboard.

![GitHub screenshot of codeblock with copy button](https://user-images.githubusercontent.com/60154347/157493654-6dfff46f-1fa4-44f4-80a4-1d95b35a3cc2.png)

On the wiki, I have to resort to copying the text like a caveman.

![libGDX screenshot of codeblock without copy button](https://user-images.githubusercontent.com/60154347/157493727-7052ecbd-424c-4c09-8ffe-62b20b4962b7.png)

I tried adding `user-select: all` to it but that caused the entire thing to get selected even when trying to highlight a specific section, which I didn't particularly like.

**Comment by crykn** [comment]
Sounds like a good idea! This discussion has some ideas (and code) on how to implement this: https://github.com/mmistakes/minimal-mistakes/discussions/2795. If you want, feel free to give it a try.
