### ISSUE TITLE
Mention JDK 11 requirement for Android development

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx.github.io#99]
Just writing this here before I forget. The Android part, I mean, but I may as well get my money's worth from this issue while I'm here.

If and when https://github.com/libgdx/libgdx/pull/6811 is merged (not anytime soon by the looks of it), [setup.md](https://github.com/libgdx/libgdx.github.io/blob/dev/wiki/start/setup.md) should be updated to note that JDK 11 or newer is required for Android development in IntelliJ IDEA.

That said, IDEA seems to come with the JetBrains Runtime (a fork of OpenJDK 11). Despite it obviously being called a "Runtime", I seem to be able to do [development](https://user-images.githubusercontent.com/60154347/166181951-2db18db7-7801-44a4-9c2f-e0a744ba148b.png) with it just fine. Am I off my rocker?

Regardless, with setting up the Android stuff without Android Studio being a bit of a pain and it being the second-class IDE for Android development, I don't suppose too many people will end up trying to run it on JDK 8.

Personally, I think Java 17 is dangerously dope, as the cool kids say, with many improvements over 8, even when using `sourceCompatibility 1.7`. But I understand this isn't enough for the skateboarders - they might want to turn it up to 18! Which is currently incompatible.

I'm hoping Gradle 7.5 will arrive shortly, but its release candidate's [due date](https://github.com/gradle/gradle/milestones) seems prone to getting pushed back. Until the final version of it arrives, it might be nice to throw up a notice about JDK 18 not working, like we had when JDKs 16 and 17 were incompatible.

Uh... one last thing: Visual Studio Code seems somewhat popular for Java/libGDX work, but I've never used it, nor do I intend to. From what I gather, users require a [Java extension or coding pack](https://code.visualstudio.com/docs/languages/java). Anyhow, it may be worth listing. I'm just unsure if it's a jack of all trades, master of none.

**Comment by crykn** [comment]
> If and when https://github.com/libgdx/libgdx/pull/6811 is merged (not anytime soon by the looks of it), [setup.md](https://github.com/libgdx/libgdx.github.io/blob/dev/wiki/start/setup.md) should be updated to note that JDK 11 or newer is required for Android development in IntelliJ IDEA.

Thanks for mentioning that! https://github.com/libgdx/libgdx/pull/6811 will likely be merged right after 1.11.0 is released, which will hopefully be in the next couple of days. 

> That said, IDEA seems to come with the JetBrains Runtime (a fork of OpenJDK 11). Despite it obviously being called a "Runtime", I seem to be able to do [development](https://user-images.githubusercontent.com/60154347/166181951-2db18db7-7801-44a4-9c2f-e0a744ba148b.png) with it just fine. Am I off my rocker?

[This page](https://www.jetbrains.com/help/idea/sdk.html#jdk) still insists on the opposite: "The bundled JRE is used for running the IDE itself, and it's not sufficient for developing Java applications. Before you start developing in Java, download and install a standalone JDK build."

> But I understand this isn't enough for the skateboarders - they might want to turn it up to 18! Which is currently incompatible. [...] It might be nice to throw up a notice about JDK 18 not working, like we had when JDKs 16 and 17 were incompatible.

22d10802a3ed639dfaee619955ff1e23fb5193da.

> Uh... one last thing: Visual Studio Code seems somewhat popular for Java/libGDX work, but I've never used it, nor do I intend to. [...] Anyhow, it may be worth listing.

If anyone has any experiences with libGDX and Visual Studio Code (the same is true for AIDE, which seems to be somewhat popular among Discord users), they are welcome to write a few sentences about any requirements that I can add to the [setup page](https://libgdx.com/wiki/start/setup).

**Comment by Frosty-J** [comment]
Oh gosh, AIDE. Yes, I think it would be helpful to write about. As bad as it is, it's possibly the best option for those who don't have access to a computer. One of the larger difficulties is libGDX and library authors usually just provide Gradle instructions and don't link to the JARs required. I have difficulty finding the JARs, and I like to think I know more than someone new to libGDX.
